spring.application.name=backoffice

spring.datasource.url=jdbc:postgresql://localhost:5432/visa
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Upload configuration
upload.dir=C:/uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
server.port=8080
server.address=localhost
